name = "FuzzifiED"
uuid = "b45b6d2d-92f2-400f-a7df-d2d897927e5f"
authors = ["Zheng Zhou"]
version = "0.10.5"

[deps]
FuzzifiED_jll = "0fc6ce7e-a225-5ad5-93a0-97260cfa1513"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SphericalHarmonics = "c489a379-e885-57ff-9236-bd896d33c250"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"

[weakdeps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
FuzzifiEDITensorsExt = ["ITensors", "ITensorMPS"]
FuzzifiEDEasySweepExt = ["ITensors", "ITensorMPS", "HDF5"]
FuzzifiEDHDF5Ext = ["HDF5"]
FuzzifiEDCUDAExt = ["CUDA"]

[compat]
FuzzifiED_jll = "0.10.5"
LinearAlgebra = "1"
SparseArrays = "1"
SphericalHarmonics = "0.1"
WignerSymbols = "2"
KrylovKit = "0.4, 0.5, 0.6, 0.7, 0.8"
ITensors = "0.6, 0.7"
ITensorMPS = "0.2, 0.3"
HDF5 = "0.14, 0.15, 0.16, 0.17"
CUDA = "5"
julia = "1.10, 1.11"
